### ISSUE TITLE
[Suggestion] Multi Site Ebb & Flow Controller

### ISSUE THREAD

**Issue by TopNumbers** [djolez/hydroponic#1]
Most people who would use this application you made are going to be doing a "[multi site ebb and flow system](http://growershouse.com/media/catalog/product/cache/1/image/512x512/9df78eab33525d08d6e5fb8d27136e95/p/g/pg30_000094-r.jpg)" where water is  shared out to 4-30 sites. [Video example here](https://www.youtube.com/watch?v=8WfRmFp6vk8)

Since you're literally the only person working on this type project in the programming world (I've been searching for months!) I can tell you without question your code will make life easier for **tons** of farmers, since every commercial solution on the market for a "[controller bucket](https://www.youtube.com/watch?v=Lm55zrSUjyw)" costs $300+ and uses cheap components (VERY cheap spa timer, when it fails, pay up another $300.) 

The main difference here is that you would utilize float switches to prevent system flooding.

The main advantage to this vs. the "flood table" setup you have is that you don't lose 2 feet of vertical growing space, and it allows for complete customization based on the space you have - and it's easily expandable if need be.

**Comment by djolez** [comment]
Thanks for the suggestion, yes I realized that since I would like to grow some bigger (maybe also different) plants the modular design would be the best, I will continue to work on this project in the future so I will definitely take it into account.
